apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: systems-clustering-bc-is
parameters:
- description: The name for image
  value: systems-clustering
  name: APPLICATION_NAME
  required: true
- name: GIT_URI
  value: https://github.com/ManageIQ/aiops-insights-clustering.git
  required: true
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      git:
        uri: ${GIT_URI}
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: 'docker.io/centos/python-36-centos7:latest'
- apiversion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    dockerImageRepository: ${APPLICATION_NAME}
    tags:
    - name: latest
    lookupPolicy:
      local: true
